module.exports = {
  apps: [
    {
      name: 'brass-backend',
      cwd: '/var/www/brass-study/backend',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        DB_HOST: '127.0.0.1',
        DB_PORT: 3306,
        DB_USERNAME: 'brass_app',
        DB_PASSWORD: 'BrassStudy2026SecureDB',
        DB_DATABASE: 'brass_study',
        JWT_SECRET: 'brass-study-jwt-prod-k8x92mNpQrS7vW3zY6bC4dFgH',
        JWT_REFRESH_SECRET: 'brass-study-refresh-prod-aB5cD8eF1gH4iJ7kL0mN3oP6q',
        FRONTEND_URL: 'https://brassphdstudy.com',
      },
    },
    {
      name: 'brass-frontend',
      cwd: '/var/www/brass-study/frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://brassphdstudy.com',
      },
    },
  ],
};
